### PR TITLE
Do not sort parameters for integration tests

### PR DESCRIPTION
**Pull request by mtsmfm**
If a flag is marked as `multiple`, following arguments are also assumed as value for a flag:

```
$ autify web test run https://app.autify.com/projects/1528/scenarios/178817 -r https://example.com=https://example.net https://example.com/foo=https://example.net/foo
📝 Using URL replacements: https://example.com => https://example.net, https://example.com/foo => https://example.net/foo
✅ Successfully started: https://app.autify.com/projects/1528/results/1899705 (Capability is Linux Chrome 110.0)
To wait for the test result, run the command below:
💻 $ autify web test wait https://app.autify.com/projects/1528/results/1899705
```

In other words, to have an integration test with `-r` option, the order matters.

```
$ autify web test run -r https://example.com=https://example.net https://app.autify.com/projects/1528/scenarios/178817
  ›   Error: Missing 1 required arg:
  ›   scenario-or-test-plan-url  Scenario URL or Test plan URL e.g. https://app.autify.com/projects/<ID>/(scenarios|test_plans)/<ID>
  ›   See more help with --help
```

```
$ autify web test run https://app.autify.com/projects/1528/scenarios/178817 -r https://example.com=https://example.net
📝 Using URL replacements: https://example.com => https://example.net
✅ Successfully started: https://app.autify.com/projects/1528/results/1899695 (Capability is Linux Chrome 110.0)
To wait for the test result, run the command below:
💻 $ autify web test wait https://app.autify.com/projects/1528/results/1899695
```

### CODE REVIEW

**Comment by 4ydx** [comment]
Maybe I'm misunderstanding something, but the current cli help says:

```
  With URL replacements:

    $ autify web test run https://app.autify.com/projects/0000/scenarios/0000 -r http://example.com=http://example.net -r http://example.org=http://example.net
```

So my understanding is that each replacement requires a `-r` parameter.  Are you wanting to change that?

**Comment by mtsmfm** [comment]
@4ydx `-r` is a shorthand for `--url-replacements`. Both should work.

```
$ autify --version                                                                                                                                                    
@autifyhq/autify-cli/0.28.0 wsl-x64 node-v18.14.2

$ autify web test run https://app.autify.com/projects/1528/scenarios/178817 -r https://example.com=https://example.net                                                
📝 Using URL replacements: https://example.com => https://example.net
✅ Successfully started: https://app.autify.com/projects/1528/results/1899866 (Capability is Linux Chrome 110.0)
To wait for the test result, run the command below:
💻 $ autify web test wait https://app.autify.com/projects/1528/results/1899866

$ autify web test run https://app.autify.com/projects/1528/scenarios/178817 --url-replacements https://example.com=https://example.net
📝 Using URL replacements: https://example.com => https://example.net
✅ Successfully started: https://app.autify.com/projects/1528/results/1899867 (Capability is Linux Chrome 110.0)
To wait for the test result, run the command below:
💻 $ autify web test wait https://app.autify.com/projects/1528/results/1899867
````

**Comment by mtsmfm** [comment]
And oclif assumes `-r foo bar` and `-r foo -r bar` are the equivalent.

**Review by 4ydx — APPROVED** [review]

**Comment by mtsmfm** [comment]
I meant, `run test -r <replacement option> <scenario url>` is parsed as `run test -r <replacement option> <replacement option2>`.

**Review by riywo — APPROVED** [review]

**Comment by mtsmfm** [comment]
@4ydx @riywo Thank you for your review!

**Pull request merged**
